language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
script: mvn compile test
install: true
notifications:
  email:
    recipients:
      - "dev.louisnam@gmail.com"
    on_success: change
    on_failure: always
